[package]
name = "eventful"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.102"
axum = "0.8.8"
chrono = { version = "0.4.44", features = ["serde"] }
md5 = "0.8.0"
prometheus = "0.14.0"
rand = "0.10.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["full"] }

[dev-dependencies]
tokio = { version = "1.49.0", features = ["full"] }